In [24]:
#!/usr/bin/env python

import numpy as np
import random


# First implement a gradient checker by filling in the following functions
def gradcheck_naive(f, x):
    """ Gradient check for a function f.

    Arguments:
    f -- a function that takes a single argument and outputs the
         cost and its gradients
    x -- the point (numpy array) to check the gradient at
    """

    rndstate = random.getstate()
    random.setstate(rndstate)
    fx, grad = f(x) # Evaluate function value at original point
    h = 1e-4        # Do not change this!
    print(fx)
    print(grad)
    # Iterate over all indexes ix in x to check the gradient.
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    print(it)
    while not it.finished:
        ix = it.multi_index
        print(ix)
        # Try modifying x[ix] with h defined above to compute numerical
        # gradients (numgrad).

        # Use the centered difference of the gradient.
        # It has smaller asymptotic error than forward / backward difference
        # methods. If you are curious, check out here:
        # https://math.stackexchange.com/questions/2326181/when-to-use-forward-or-central-difference-approximations

        # Make sure you call random.setstate(rndstate)
        # before calling f(x) each time. This will make it possible
        # to test cost functions with built in randomness later.

        ### YOUR CODE HERE:
        xt = x[ix]
        x[ix] = xt-h
        random.setstate(rndstate)
        f1,g1 = f(x)
        x[ix] = xt+h
        random.setstate(rndstate)
        f2,g2 = f(x)

        numgrad = (f2-f1)/(2*h)
        x[ix]=xt
        ### END YOUR CODE

        # Compare gradients
        reldiff = abs(numgrad - grad[ix]) / max(1, abs(numgrad), abs(grad[ix]))
        if reldiff > 1e-5:
            print("Gradient check failed.")
            print("First gradient error found at index %s" % str(ix))
            print("Your gradient: %f \t Numerical gradient: %f" % (
                grad[ix], numgrad))
            return

        it.iternext() # Step to next dimension



def sanity_check():
    """
    Some basic sanity checks.
    """
    quad = lambda x: (np.sum(x ** 2), x * 2)

    gradcheck_naive(quad, np.array(123.456))      # scalar test
    gradcheck_naive(quad, np.random.randn(3,))    # 1-D test
    gradcheck_naive(quad, np.random.randn(4,5))   # 2-D test





if __name__ == "__main__":
    sanity_check()



15241.383936
246.912
()
3.26035353777
[-0.30406001  3.00298703  1.98268266]
(0,)
(1,)
(2,)
22.9580114633
[[ 0.50885058 -4.89237779  1.51633071  4.02717514 -0.95448464]
 [ 0.20752995  0.93955795  1.06232495  3.2684255  -2.21717114]
 [-0.59243366  1.03404827  4.02002748  0.22242829  0.96079592]
 [-1.77194591  0.52658939 -0.97523128  2.7609527  -0.10958953]]
(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)


In [15]:
quad = lambda x: (np.sum(x ** 2), x * 2)
quad(3)

(9, 6)